name: Tests

on:
  push:
    branches:
      - main

jobs:
  Test:
    name: Check the code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make install

      - name: Linter
        run: make lint

      - name: Tests
        run: make coverage
